-- ===========================================================================
-- The Blueprint — notifications setup has been split in two
--
-- Bundling the schema with the cron meant neither could be applied without the
-- other, and the schema is a prerequisite for the function working at all.
-- Applying it should never have required also scheduling hourly sends.
--
--   supabase/notifications-schema.sql   PART A. Tables and columns.
--                                       Safe to run now. Schedules nothing.
--
--   supabase/notifications-cron.sql     PARTS B and C. Vault secrets and the
--                                       hourly job. Run only after the smoke
--                                       test passes.
--
-- Run Part A, re-run the smoke test, and only then consider the cron file.
-- ===========================================================================
